FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /var/www/app

COPY . .

RUN dotnet restore

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime

WORKDIR /var/www/app

COPY --from=build /var/www/app .

EXPOSE 5089

CMD ["dotnet", "run"]