name: pomtools

services:
  node:
    image: node:lts-alpine
    volumes:
      - .:/var/www/app
    working_dir: /var/www/app/PomToolbox
    command: >
      sh -c "
        npm install
        npm run dev
        tail -f /dev/null
        "
  
  dotnet:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    volumes:
      - .:/var/www/app
    working_dir: /var/www/app/PomToolbox
    command: >
      sh -c "
        dotnet restore
        dotnet watch
        "

    ports:
      - "5089:5089"