version: '3.8'

services:
  pomtools:
    build:
      context: .
      dockerfile: Dockerfile.dotnet.prod
    volumes:
      - ./PomToolbox/.env:/var/www/app/.env
      - ./certs:/var/www/app/certs
      - ./PomTools/Data/app.db:/var/www/app/PomToolbox/Data/app.db
    ports:
      - "80:8080"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped