version: '3.8'

services:
  pomtools:
    build:
      context: .
      dockerfile: Dockerfile.dotnet.prod
    volumes:
      - ./PomToolbox/.env:/var/www/app/.env
      - ./certs:/var/www/app/certs
    ports:
      - "80:8080"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped