name: pomtools
services:
  tailwind:
    image: node:lts-alpine
    volumes:
      - app-data:/var/www/app
    working_dir: /var/www/app/PomToolbox
    command: >
      sh -c "
        npm install &&
        npm run dev &&
        tail -f /dev/null
      "
    depends_on:
      - dotnet

  dotnet:
    build:
      context: .
      dockerfile: Dockerfile.dotnet
    volumes:
      - app-data:/var/www/app
      - .git:/var/www/app/.git
      - .gitignore:/var/www/app/.gitignore
    working_dir: /var/www/app
    command: tail -f /dev/null

    ports:
      - "5089:5089"

volumes:
  app-data: