name: pomtools
services:
  tailwind:
    image: node:lts-alpine
    volumes:
      - app-data:/var/www/app
    working_dir: /var/www/app/PomToolbox
    command: >
      sh -c "
        npm install &&
        tail -f /dev/null
      "

  dotnet:
    build:
      context: .
      dockerfile: Dockerfile.dotnet
    volumes:
      - app-data:/var/www/app
      - .git:/var/www/app/.git
      - .gitignore:/var/www/app/.gitignore
    working_dir: /var/www/app
    command: >
      sh -c "
        dotnet restore &&
        tail -f /dev/null
      "
    ports:
      - "5089:5089"

volumes:
  app-data: