FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /var/www/app

COPY . .

RUN dotnet restore

RUN dotnet tool install --global dotnet-ef
RUN export PATH="$PATH:/root/.dotnet/tools"
WORKDIR /var/www/app/PomToolbox
RUN dotnet ef database update
RUN dotnet dev-certs https --format PEM --export-path ./certs/temp_cert.pem --no-password

WORKDIR /var/www/app

EXPOSE 5089